test-your-pr: fix bot comment: actions/github-script is much better [skip ci]
Signed-off-by: Jerry <isjerryxiao@outlook.com>

diff --git a/.github/workflows/test-your-pr.yml b/.github/workflows/test-your-pr.yml
--- a/.github/workflows/test-your-pr.yml
+++ b/.github/workflows/test-your-pr.yml
@@ -52,11 +52,16 @@ jobs:
     runs-on: ubuntu-20.04
     if: ${{ always() && contains(needs.build.result, 'success') }}
     steps:
-      - uses: thollander/actions-comment-pull-request@v2
+      - uses: actions/github-script@v7
         with:
-          token: ${{ secrets.COMMENT_GITHUB_TOKEN }}
-          message: |
-            Congratulations! Your pull request passed the check.
+          github-token: ${{secrets.COMMENT_GITHUB_TOKEN}}
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: 'Congratulations! Your pull request passed the check.'
+            })
 
   comment_failure:
     needs: [build]
@@ -65,11 +70,18 @@ jobs:
     steps:
       - shell: bash
         run: |
-          echo ${{needs.build.outputs.generate_roa}} | base64 -d |tail > /tmp/buildjob_tail.log || echo 'internal error' > /tmp/buildjob_tail.log
+          echo ${{needs.build.outputs.generate_roa}} | base64 -d | tr -d '`' |tail > /tmp/buildjob_tail.log || echo 'internal error' > /tmp/buildjob_tail.log
 
-      - uses: thollander/actions-comment-pull-request@v2
+      - uses: actions/github-script@v7
         with:
-          token: ${{ secrets.COMMENT_GITHUB_TOKEN }}
-          filePath: /tmp/buildjob_tail.log
+          github-token: ${{secrets.COMMENT_GITHUB_TOKEN}}
+          script: |
+            const fs = require('fs')
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: fs.readFileSync('/tmp/buildjob_tail.log')
+            })
 
       - run: false
